version: '3.3'

services:

  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: --log-facility=- --server=8.8.8.8 --neg-ttl=3600 --cache-size=1000 --max-cache-ttl=3600 --min-cache-ttl=3600 --all-servers
    cap_add: 
      - NET_ADMIN
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
    links:
      - proxy:www.nrm.se
      - proxy:local.nrm.se
      - proxy:local.naturforskaren.se

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  web2:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=www.nrm.se

  web3:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=local.nrm.se

  web4:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=local.naturforskaren.se

  web5:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=naturforskaren.se

