version: '3.1'

services:
      
  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: --log-facility=- --server=127.0.0.11 --server=193.10.57.11 --server=8.8.8.8 --server=172.16.0.72 --server=172.16.0.7 --neg-ttl=3600 --cache-size=1000 --max-cache-ttl=3600 --min-cache-ttl=3600 --all-servers
    cap_add: 
      - NET_ADMIN
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
    links:
      - proxy:naturforskaren.se
      - proxy:www.naturforskaren.se
      - proxy:beta.naturforskaren.se

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  web1:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=naturforskaren.se

  web2:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=www.naturforskaren.se

  web3:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=beta.naturforskaren.se


