version: '3.7'

services:

  proxy:
    image: jwilder/nginx-proxy:0.4.0
    container_name: jwilder-proxy
    environment: 
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      #- ./nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro

  web1:
    image: nginx:alpine
    container_name: wildcard-local.nrm
    environment:
      - VIRTUAL_HOST=local.nrm.se
